cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
      path:
          avatar: avatar
    credentials:
      access-key: ${S3_BUCKET_ACCESS_KEY}
      secret-key: ${S3_BUCKET_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false