
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASS}

  jpa :
    hibernate:
      ddl-auto : create-drop
    properties:
      hibernate :
        #show_sql : true #??? ??? ??
        format_sql : true #??? ??

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type : trace