name: Brandol CI/CD

on:
  push:
    branches:
      - Feat/5
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      shell: bash
    - name: Generate deployment package
      run: |
        mkdir -p deploy
        cp build/libs/*.jar deploy/application.jar
        cp Procfile deploy/Procfile
        cp -r .ebextensions-dev deploy/.ebextensions
        cp -r .platform deploy/.platform
        cd deploy && zip -r deploy.zip .



